version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: inventory_db
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistencia de datos
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d inventory_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .  # Construye la imagen usando el Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/inventory_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: secret
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy  # Espera a que la BD esté lista

volumes:
  postgres_data:  # Volumen para persistir datos de PostgreSQL